version: "3.9"

services:
  nexign-database:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-net
    volumes:
      - /var/lib/postgresql/data
    restart: always

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: always
    networks:
      - kafka-net
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: always
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    networks:
      - kafka-net
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  liquibase:
    image: liquibase/liquibase:4.17.2
    networks:
      - app-net
    command: liquibase --driver=org.postgresql.Driver --url=jdbc:postgresql://nexign-database:5432/postgres --password=postgres --username=postgres --changelog-file=/boot/db.changelog-master.xml update
    volumes:
      - ./liquibase/changelog:/liquibase/boot/changelog
      - ./liquibase/changelog/db.changelog-master.xml:/liquibase/boot/db.changelog-master.xml
      - ./liquibase/changelog/changelog-1.0.0.xml:/liquibase/boot/changelog-1.0.0.xml
      - ./liquibase/changelog/changelog-1.0.1.xml:/liquibase/boot/changelog-1.0.1.xml
    depends_on:
      - nexign-database

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
  app-net:
    name: app-net
    driver: bridge

