spring:
  application:
    name: cdr

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${POSTGRES_DATABASE}
    url: ${POSTGRES_URL}
    username:  ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

kafka:
  url: ${BOOTSTRAP_SERVERS_CONFIG}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

server:
  port: 7652

call:
  duration:
    max: 1000

cdr:
  generate:
    path: cdr.txt
    count:
      abonent: 10
      cdr: 100
    balance:
      range: 300

randommer:
  api:
    key: 6fcfa6533e004c9ebbe31f3ca4d44de4
    country_code: RU
    count: 10
