spring:
  application:
    name: cdr

  datasource:
    driver-class-name: org.postgresql.Driver
    name: nexign
    url: jdbc:postgresql://localhost:5434/nexign
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7652

call:
  duration:
    max: 1000

cdr:
  generate:
    path: cdr.txt
    count:
      abonent: 10
      cdr: 100
    balance:
      range: 300

randommer:
  api:
    key: 6fcfa6533e004c9ebbe31f3ca4d44de4
    country_code: RU
    count: 10
