spring:
  application:
    name: cdr

  datasource:
    driver-class-name: org.postgresql.Driver
    name: nexign
    url: jdbc:postgresql://localhost:5434/nexign
    username: postgres
    password: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7652

call:
  duration:
    max: 3600

cdr:
  generate:
    path: cdr.txt
    count:
      abonent: 50
      cdr: 50
    balance:
      range: 500

randommer:
  api:
    key: 6fcfa6533e004c9ebbe31f3ca4d44de4
    country_code: RU
    count: 1