spring:
  application:
    name: hrs

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${POSTGRES_DATABASE}
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: false

kafka:
  url: ${BOOTSTRAP_SERVERS_CONFIG}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

server:
  port: 7654

cdr:
  generate:
    plus-cdr-path: cdr-plus.txt

  ordinary:
    fixed-count-minute: 100

  unlimited:
    fixed-count-minute: 100
