spring:
  application:
    name: common

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${POSTGRES_DATABASE}
    url: ${POSTGRES_URL}
    username:  ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
server:
  port: 8766

