spring:
  application:
    name: crm

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${POSTGRES_DATABASE}
    url: ${POSTGRES_URL}
    username:  ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

server:
  port: 7643

jwt:
  token:
    expired: 3600000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yaml