spring:
  application:
    name: crm

  datasource:
    driver-class-name: org.postgresql.Driver
    name: nexign
    url: jdbc:postgresql://localhost:5434/nexign
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7653

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yaml