spring:
  application:
    name: brt

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${POSTGRES_DATABASE}
    url: ${POSTGRES_URL}
    username:  ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

kafka:
  url: ${BOOTSTRAP_SERVERS_CONFIG}

server:
  port: 7651

cdr:
  generate:
    path: cdr.txt
    plus-cdr-path: cdr-plus.txt

nexign:
  send-hrs-topic: hrs-topic
  reply-topics-brt: brt-reply-topic


