spring:
  application:
    name: brt

  datasource:
    driver-class-name: org.postgresql.Driver
    name: nexign
    url: jdbc:postgresql://localhost:5434/nexign
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7651

cdr:
  generate:
    path: cdr.txt
    plus-cdr-path: cdr-plus.txt

nexign:
  send-hrs-topic: hrs-topic
  reply-topics-brt: brt-reply-topic


